# Generated by Django 5.2.1 on 2025-05-24 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_class_enrolled_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Week 1: Introduction to Algebra', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='lesson_materials/%Y/%m/%d/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_materials', to='academics.class')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lesson_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date', 'title'],
            },
        ),
    ]
