# Generated by Django 5.2.1 on 2025-05-24 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_class_enrolled_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=150)),
                ('grade', models.CharField(max_length=20)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_for_class', to='academics.class')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded', 'class_instance__name', 'assessment_name'],
                'unique_together': {('student', 'class_instance', 'assessment_name')},
            },
        ),
    ]
